### ISSUE TITLE
Excluded character combination not taken into account

### ISSUE THREAD

**Issue by edwardmp** [ariejan/license_plate_validator#9]
Thanks for publishing this, very useful.
Only thing I noted is that the algorithm does not take the "forbidden" character combinations in account (like GVD, PVV etc, see https://nl.wikipedia.org/wiki/Nederlands_kenteken#Huidige_situatie).

I can probably modify the code to support this, but I'm not sure if that's the intended behavior of this library (we probably can't find exactly all combinations that can't be used). Let me know.

**Comment by ariejan** [comment]
Good point. At [RDW](https://www.rdw.nl/Particulier/Paginas/Uitleg-over-de-cijfers-en-letters-op-de-kentekenplaat.aspx) (Dutch) I find the following:

> Sinds kentekencombinatie 4 gebruikt de RDW geen klinkers meer in het kenteken (met uitzondering van het kenteken voor opleggers). De letter C en Q gebruikt de RDW ook niet omdat deze letters teveel op een nul lijken.  Naast de afkorting van een politieke partij worden de volgende lettercombinaties ook niet gebruikt: GVD, KKK, NSB, PKK, PSV, TBS, SS en SD. 

This appear to be a complete list, although "political parties" is still a bit vague. 

I'd welcome a pull request for this, but maybe add these letter combinations as a separate options that's off by default for compatibility reasons.

Do you need any help with implementing this and creating the pull request?

**Comment by ariejan** [comment]
@edwardmp going to close this PR. If you feel it's still relevant, just open a new issue or PR.
